# Generated by Django 4.2.1 on 2023-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(verbose_name='Описание'),
        ),
    ]
